### ISSUE TITLE
lodash build triggers a pending deprecations in Node.js

### ISSUE THREAD

**Issue by targos** [poppinss/utils#17]
```
(node:18230) [DEP0111] DeprecationWarning: process.binding() is deprecated. Please use public APIs instead.
    at /Users/targos/git/targos/adonis-experiments/node_modules/@poppinss/utils/build/src/lodash/index.js:37:31
    at Object.<anonymous> (/Users/targos/git/targos/adonis-experiments/node_modules/@poppinss/utils/build/src/lodash/index.js:37:58)
    at Object.<anonymous> (/Users/targos/git/targos/adonis-experiments/node_modules/@poppinss/utils/build/src/lodash/index.js:43:452)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/targos/git/targos/adonis-experiments/node_modules/@poppinss/utils/build/index.js:36:31)
```

This was fixed in lodash back in 2018: https://github.com/lodash/lodash/commit/363fef0efcf3270ab254fddd0deff12579ce7a26
Is it possible to use a more recent version?

**Comment by thetutlage** [comment]
I am using the lodash cli to create a small build of only the functions we need and it looks like, the CLI build is not using the latest code?

**Comment by targos** [comment]
Unfortunately, it looks like the lodash CLI is no longer maintained and uses an old version of lodash: https://github.com/lodash-archive/lodash-cli/blob/master/package.json#L25

**Comment by targos** [comment]
What's the reason for not depending on `lodash` directly in this project?

**Comment by targos** [comment]
You can always import only the functions that you need with `import ... from 'lodash/function'`

**Comment by thetutlage** [comment]
Couple of issues.

The typings of lodash are so big. Last time I ran the diagnostics, it has over 200k types and slows down typescript compiler

Lodash has also published their individual functions as npm packages, but then they are also outdated. For example this https://www.npmjs.com/package/lodash.get

**Comment by targos** [comment]
> The typings of lodash are so big. Last time I ran the diagnostics, it has over 200k types and slows down typescript compiler

The typings are in a separate package, so you do not have to install them. You can keep an internal definition file for the functions that you use (similar to the existing https://github.com/poppinss/utils/blob/develop/src/lodash/index.ts)

**Comment by targos** [comment]
Proposed fix: https://github.com/poppinss/utils/pull/18
