### ISSUE TITLE
Attempting to Install Adonis v5 Results in Error

### ISSUE THREAD

**Issue by smilingkylan** [poppinss/utils#21]
Tried using node v12.6 on a Mac with the command `npm init adonis-ts-app@latest decide-adonis-2`, and got this error message:

```
kylans-mbp:decide kylan$ npm init adonis-ts-app@latest decide-adonis-2
npx: installed 193 in 7.925s
/Users/kylan/.npm/_npx/3299/lib/node_modules/create-adonis-ts-app/node_modules/@poppinss/utils/build/src/Helpers/string.js:241
        return `${values[0]}${options?.pairSeparator || ' and '}${values[1]}`;
                                      ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/kylan/.npm/_npx/3299/lib/node_modules/create-adonis-ts-app/node_modules/@poppinss/utils/build/src/Helpers/index.js:56:31)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)

```

**Comment by targos** [comment]
AFAIK AdonisJS v5 only supports Node.js from v14.

**Comment by targos** [comment]
Yes, this is precised in the documentation: https://docs.adonisjs.com/guides/installation
Only Node.js v14.15.4 and later are supported.

**Comment by smilingkylan** [comment]
Ok thank you for the heads up!
